preprocessor:
  cls: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  params:
    normalize: per_feature
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: hann
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
    stft_conv: false
spec_augment:
  cls: nemo.collections.asr.modules.SpectrogramAugmentation
  params:
    rect_freq: 50
    rect_masks: 5
    rect_time: 120

a_model_name: QuartzNet15x5Base-En # CHANGE
sample_rate: 16000
labels: 
  - ' '
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - n
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - y
  - z
  - ''''
train_ds:
  manifest_filepath: /disk1/it1/annotations/manifest_train.json # CHANGE
  video_frame_rate: 5 # CHANGE
  # - - /data2/nemo_asr/nemo_asr_set_3.0/bucket1/tarred_audio_manifest.json #TBD # CHANGE
  sample_rate: 16000
  batch_size: 1 # CHANGE
  shuffle: true
  num_workers: 0 # CHANGE
  pin_memory: true
  use_start_end_token: false
  trim_silence: false
  max_duration: 20.0 # CHANGE
  min_duration: 0.1
  is_tarred: false
  tarred_audio_filepaths: null # CHANGE
  shuffle_n: 2048
  bucketing_strategy: synced_randomized
  bucketing_batch_size:
  - 34
  - 30
  - 26
  - 22
  - 18
  - 16
  - 12
  - 8

validation_ds:
  manifest_filepath: /disk1/it1/annotations/manifest_train.json # CHANGE
  video_frame_rate: 5 # CHANGE
  # - /manifests/librispeech/librivox-dev-other.json #TBD # CHANGE
  sample_rate: 16000
  batch_size: 1
  shuffle: false
  num_workers: 0
  pin_memory: true
  use_start_end_token: false
test_ds:
  manifest_filepath: /disk1/it1/annotations/manifest_train.json
  # - /manifests/librispeech/librivox-dev-other.json #TBD
  sample_rate: 16000
  batch_size: 1
  shuffle: false
  num_workers: 0
  pin_memory: true
  use_start_end_token: false

av_encoder: # CHANGE
  d_model: 512
  nhead: 4
  num_layers: 2
  dropout: 0.1

v_model: # CHANGE
  feat_dim: 512

decoder:
  cls: nemo.collections.asr.modules.ConvASRDecoder
  params:
    feat_in: 512
    num_classes: 28
    vocabulary:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - y
    - z
    - ''''
optim:
  name: novograd
  lr: 0.01
  betas:
  - 0.8
  - 0.5
  weight_decay: 0.001
target: nemo.collections.asr.models.av_ctc_bpe_models.AV_EncDecCTCModel
